 # Sort, Search & Counting Functions

In [1]:
import numpy as np

In [3]:
arr = np.array([4,3,34,5,4,3,3,5,6,89])

In [4]:
arr

array([ 4,  3, 34,  5,  4,  3,  3,  5,  6, 89])

In [5]:
np.sort(arr)

array([ 3,  3,  3,  4,  4,  5,  5,  6, 34, 89])

In [6]:
np.searchsorted(arr,34)

9

In [8]:
arr1 = np.array([0,4938,48,5484,384,9584,83, 0 ,0 ,0])

In [9]:
np.count_nonzero(arr1) # It counts non-zero data.

6

In [10]:
arr

array([ 4,  3, 34,  5,  4,  3,  3,  5,  6, 89])

In [11]:
# Find the index of data which is greater than 6
np.where(arr > 6)

(array([2, 9]),)

In [13]:
np.extract(arr>3 , arr) # To extract data 

array([ 4, 34,  5,  4,  5,  6, 89])

# Numpy - Byte Swapping

In [15]:
arr.byteswap() # To convert into bytes

array([ 288230376151711744,  216172782113783808, 2449958197289549824,
        360287970189639680,  288230376151711744,  216172782113783808,
        216172782113783808,  360287970189639680,  432345564227567616,
       6413125869375586304])

# Numpy - Copies & Views.

In [16]:
arr

array([ 4,  3, 34,  5,  4,  3,  3,  5,  6, 89])

In [17]:
a = np.copy(arr)  # data will copied into a but different locations. so, if we change any data in 'arr' then it will not affect 'a'.

In [18]:
a

array([ 4,  3, 34,  5,  4,  3,  3,  5,  6, 89])

In [19]:
b = arr.view() # In this, It will affect, if we change any one of them.

In [20]:
b

array([ 4,  3, 34,  5,  4,  3,  3,  5,  6, 89])

In [22]:
b[0] = 67

In [23]:
b

array([67,  3, 34,  5,  4,  3,  3,  5,  6, 89])

In [24]:
arr

array([67,  3, 34,  5,  4,  3,  3,  5,  6, 89])

# Numpy - Matrix library.

In [25]:
import numpy.matlib as nm

In [26]:
nm.zeros(5) # Generate matrix 

matrix([[0., 0., 0., 0., 0.]])

In [27]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [29]:
nm.eye(5)  # Identity matrix genereted

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

# Numpy - Linear Algebra

In [38]:
arr1 = np.random.randint([[2,4],[3,4]])

In [39]:
arr2 = np.random.randint([[2,4],[3,4]])

In [40]:
np.dot(arr1,arr2) # Matrix multiplication

array([[0, 2],
       [0, 0]])

In [41]:
arr1@arr2  # Matrix multiplication

array([[0, 2],
       [0, 0]])